import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
await page.goto('http://localhost:4173/')
await page.screenshot({ path: 'shots/m-landing.png' })
await page.fill('#subject', process.argv[2] ?? 'npub1sg6plzptd64u62a878hep2kev88swjh3tw00gjsfl8f237lmu63q0uf63m')
await page.click('button[type=submit]')
await page.waitForSelector('text=File complete', { timeout: 120000 })
await page.waitForTimeout(500)
const w = await page.evaluate(() => document.documentElement.scrollWidth)
console.log('scrollWidth', w)
await page.evaluate(() => document.querySelector('.cover').scrollIntoView())
await page.screenshot({ path: 'shots/m-cover.png' })
await page.evaluate(() => document.getElementById('money').scrollIntoView())
await page.screenshot({ path: 'shots/m-money.png' })
await browser.close()
